/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *Fischer) Reset()      { *m = Fischer{} }
func (*Fischer) ProtoMessage() {}
func (*Fischer) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4886d844e21c51a, []int{0}
}
func (m *Fischer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fischer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Fischer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fischer.Merge(m, src)
}
func (m *Fischer) XXX_Size() int {
	return m.Size()
}
func (m *Fischer) XXX_DiscardUnknown() {
	xxx_messageInfo_Fischer.DiscardUnknown(m)
}

var xxx_messageInfo_Fischer proto.InternalMessageInfo

func (m *FischerList) Reset()      { *m = FischerList{} }
func (*FischerList) ProtoMessage() {}
func (*FischerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4886d844e21c51a, []int{1}
}
func (m *FischerList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FischerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FischerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FischerList.Merge(m, src)
}
func (m *FischerList) XXX_Size() int {
	return m.Size()
}
func (m *FischerList) XXX_DiscardUnknown() {
	xxx_messageInfo_FischerList.DiscardUnknown(m)
}

var xxx_messageInfo_FischerList proto.InternalMessageInfo

func (m *Flunder) Reset()      { *m = Flunder{} }
func (*Flunder) ProtoMessage() {}
func (*Flunder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4886d844e21c51a, []int{2}
}
func (m *Flunder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Flunder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *Flunder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flunder.Merge(m, src)
}
func (m *Flunder) XXX_Size() int {
	return m.Size()
}
func (m *Flunder) XXX_DiscardUnknown() {
	xxx_messageInfo_Flunder.DiscardUnknown(m)
}

var xxx_messageInfo_Flunder proto.InternalMessageInfo

func (m *FlunderList) Reset()      { *m = FlunderList{} }
func (*FlunderList) ProtoMessage() {}
func (*FlunderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4886d844e21c51a, []int{3}
}
func (m *FlunderList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FlunderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FlunderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlunderList.Merge(m, src)
}
func (m *FlunderList) XXX_Size() int {
	return m.Size()
}
func (m *FlunderList) XXX_DiscardUnknown() {
	xxx_messageInfo_FlunderList.DiscardUnknown(m)
}

var xxx_messageInfo_FlunderList proto.InternalMessageInfo

func (m *FlunderSpec) Reset()      { *m = FlunderSpec{} }
func (*FlunderSpec) ProtoMessage() {}
func (*FlunderSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4886d844e21c51a, []int{4}
}
func (m *FlunderSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FlunderSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FlunderSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlunderSpec.Merge(m, src)
}
func (m *FlunderSpec) XXX_Size() int {
	return m.Size()
}
func (m *FlunderSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FlunderSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FlunderSpec proto.InternalMessageInfo

func (m *FlunderStatus) Reset()      { *m = FlunderStatus{} }
func (*FlunderStatus) ProtoMessage() {}
func (*FlunderStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_c4886d844e21c51a, []int{5}
}
func (m *FlunderStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FlunderStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FlunderStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlunderStatus.Merge(m, src)
}
func (m *FlunderStatus) XXX_Size() int {
	return m.Size()
}
func (m *FlunderStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FlunderStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FlunderStatus proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Fischer)(nil), "k8s.io.sample_apiserver.pkg.apis.wardle.v1alpha1.Fischer")
	proto.RegisterType((*FischerList)(nil), "k8s.io.sample_apiserver.pkg.apis.wardle.v1alpha1.FischerList")
	proto.RegisterType((*Flunder)(nil), "k8s.io.sample_apiserver.pkg.apis.wardle.v1alpha1.Flunder")
	proto.RegisterType((*FlunderList)(nil), "k8s.io.sample_apiserver.pkg.apis.wardle.v1alpha1.FlunderList")
	proto.RegisterType((*FlunderSpec)(nil), "k8s.io.sample_apiserver.pkg.apis.wardle.v1alpha1.FlunderSpec")
	proto.RegisterType((*FlunderStatus)(nil), "k8s.io.sample_apiserver.pkg.apis.wardle.v1alpha1.FlunderStatus")
}

func init() {
	proto.RegisterFile("k8s.io/sample-apiserver/pkg/apis/wardle/v1alpha1/generated.proto", fileDescriptor_c4886d844e21c51a)
}

var fileDescriptor_c4886d844e21c51a = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0xee, 0x6f, 0x5d, 0xca, 0x9f, 0x1c, 0x50, 0xd5, 0x43, 0x3a, 0xf5, 0xb4, 0xcb,
	0xec, 0x76, 0x42, 0x08, 0x0e, 0x08, 0x14, 0xa1, 0x0a, 0x24, 0x10, 0x52, 0x40, 0x1c, 0x10, 0x62,
	0xb8, 0xc9, 0xbb, 0x34, 0x34, 0x69, 0x2c, 0xdb, 0xed, 0xb4, 0x1b, 0x47, 0x8e, 0x7c, 0x17, 0xc4,
	0x77, 0xa8, 0xc4, 0x65, 0xc7, 0x9d, 0x2a, 0x1a, 0xbe, 0x05, 0x27, 0x14, 0xdb, 0x6d, 0xba, 0x95,
	0x09, 0xb6, 0x03, 0x12, 0xb7, 0x3c, 0xb6, 0x9f, 0xe7, 0xfd, 0xbd, 0xf6, 0xab, 0xa0, 0x47, 0x83,
	0x7b, 0x02, 0x47, 0x29, 0x11, 0x34, 0x61, 0x31, 0xec, 0x51, 0x16, 0x09, 0xe0, 0x63, 0xe0, 0x84,
	0x0d, 0x42, 0x92, 0x2b, 0x72, 0x44, 0x79, 0x10, 0x03, 0x19, 0x77, 0x68, 0xcc, 0xfa, 0xb4, 0x43,
	0x42, 0x18, 0x02, 0xa7, 0x12, 0x02, 0xcc, 0x78, 0x2a, 0x53, 0xbb, 0xad, 0x13, 0xb0, 0x4e, 0x38,
	0x58, 0x24, 0x60, 0x36, 0x08, 0x71, 0xae, 0xb0, 0x4e, 0xc0, 0xf3, 0x84, 0xc6, 0x5e, 0x18, 0xc9,
	0xfe, 0xa8, 0x87, 0xfd, 0x34, 0x21, 0x61, 0x1a, 0xa6, 0x44, 0x05, 0xf5, 0x46, 0x87, 0x4a, 0x29,
	0xa1, 0xbe, 0x74, 0x81, 0xc6, 0x1d, 0x83, 0x48, 0x59, 0x94, 0x50, 0xbf, 0x1f, 0x0d, 0x81, 0x1f,
	0x17, 0x78, 0x09, 0x48, 0x4a, 0xc6, 0x2b, 0x58, 0x0d, 0x72, 0x91, 0x8b, 0x8f, 0x86, 0x32, 0x4a,
	0x60, 0xc5, 0x70, 0xf7, 0x4f, 0x06, 0xe1, 0xf7, 0x21, 0xa1, 0xe7, 0x7d, 0xad, 0x2f, 0x16, 0xda,
	0xea, 0x46, 0xf9, 0x26, 0xb7, 0xdf, 0xa3, 0xed, 0x9c, 0x27, 0xa0, 0x92, 0xd6, 0xad, 0x1d, 0x6b,
	0xb7, 0xba, 0xdf, 0xc6, 0xe6, 0x7a, 0x96, 0x63, 0x8b, 0xab, 0xc9, 0x4f, 0xe3, 0x71, 0x07, 0xbf,
	0xe8, 0x7d, 0x00, 0x5f, 0x3e, 0x07, 0x49, 0x5d, 0x7b, 0x32, 0x6d, 0x96, 0xb2, 0x69, 0x13, 0x15,
	0x6b, 0xde, 0x22, 0xd5, 0xee, 0x22, 0x3b, 0x88, 0x04, 0x8d, 0xe3, 0xf4, 0x08, 0x82, 0x6e, 0x3c,
	0x1a, 0x06, 0xc0, 0x45, 0xbd, 0xbc, 0xb3, 0xb6, 0x5b, 0x71, 0x6f, 0x67, 0xd3, 0xa6, 0xfd, 0x78,
	0x65, 0xd7, 0xfb, 0x8d, 0xa3, 0xf5, 0xcd, 0x42, 0x55, 0x43, 0xfd, 0x2c, 0x12, 0xd2, 0x7e, 0xbb,
	0x42, 0x8e, 0xff, 0x8e, 0x3c, 0x77, 0x2b, 0xee, 0x9b, 0x86, 0x7b, 0x7b, 0xbe, 0xb2, 0x44, 0xfd,
	0x0e, 0x6d, 0x44, 0x12, 0x12, 0x0d, 0x5a, 0xdd, 0xbf, 0x8f, 0x2f, 0x3b, 0x33, 0xd8, 0xb0, 0xba,
	0x35, 0x53, 0x65, 0xe3, 0x69, 0x9e, 0xe7, 0xe9, 0xd8, 0xd6, 0xd7, 0x32, 0xda, 0x32, 0xad, 0xfd,
	0x83, 0x37, 0x38, 0x40, 0xeb, 0x82, 0x81, 0x5f, 0x2f, 0xab, 0xf4, 0x07, 0x57, 0x68, 0x46, 0xa3,
	0xbe, 0x64, 0xe0, 0xbb, 0xd7, 0x4c, 0xa9, 0xf5, 0x5c, 0x79, 0x2a, 0xd8, 0x0e, 0xd1, 0xa6, 0x90,
	0x54, 0x8e, 0x44, 0x7d, 0x4d, 0x95, 0x78, 0x78, 0xf5, 0x12, 0x2a, 0xc6, 0xbd, 0x6e, 0x8a, 0x6c,
	0x6a, 0xed, 0x99, 0x78, 0x3d, 0x05, 0xfa, 0xe4, 0xff, 0x31, 0x05, 0x9a, 0xf5, 0x82, 0x29, 0xf8,
	0x54, 0x74, 0x93, 0x5f, 0xa6, 0x4d, 0x50, 0x85, 0xc3, 0x21, 0x70, 0x18, 0xfa, 0xa0, 0xda, 0xa9,
	0xb8, 0xb7, 0x8c, 0xb1, 0xe2, 0xcd, 0x37, 0xbc, 0xe2, 0x8c, 0xfd, 0x04, 0xd5, 0x16, 0xe2, 0xd5,
	0x31, 0x03, 0xf5, 0xc2, 0x15, 0xb7, 0x95, 0x4d, 0x9b, 0x35, 0x6f, 0x79, 0xe3, 0xe7, 0xf9, 0x05,
	0xef, 0xac, 0xb1, 0x75, 0x03, 0xd5, 0xce, 0xbe, 0xc0, 0xeb, 0xc9, 0xcc, 0x29, 0x9d, 0xcc, 0x9c,
	0xd2, 0xe9, 0xcc, 0x29, 0x7d, 0xcc, 0x1c, 0x6b, 0x92, 0x39, 0xd6, 0x49, 0xe6, 0x58, 0xa7, 0x99,
	0x63, 0x7d, 0xcf, 0x1c, 0xeb, 0xf3, 0x0f, 0xa7, 0xf4, 0xa6, 0x7d, 0xd9, 0xbf, 0xf1, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x49, 0x66, 0x39, 0x27, 0xc0, 0x05, 0x00, 0x00,
}

func (m *Fischer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fischer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fischer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DisallowedFlunders) > 0 {
		for iNdEx := len(m.DisallowedFlunders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.DisallowedFlunders[iNdEx])
			copy(dAtA[i:], m.DisallowedFlunders[iNdEx])
			i = encodeVarintGenerated(dAtA, i, uint64(len(m.DisallowedFlunders[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FischerList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FischerList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FischerList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Flunder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Flunder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Flunder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FlunderList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FlunderList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FlunderList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FlunderSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FlunderSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FlunderSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ReferenceType != nil {
		i -= len(*m.ReferenceType)
		copy(dAtA[i:], *m.ReferenceType)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.ReferenceType)))
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.Reference)
	copy(dAtA[i:], m.Reference)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Reference)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FlunderStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FlunderStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FlunderStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Fischer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.DisallowedFlunders) > 0 {
		for _, s := range m.DisallowedFlunders {
			l = len(s)
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *FischerList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *Flunder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *FlunderList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *FlunderSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Reference)
	n += 1 + l + sovGenerated(uint64(l))
	if m.ReferenceType != nil {
		l = len(*m.ReferenceType)
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *FlunderStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Fischer) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Fischer{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`DisallowedFlunders:` + fmt.Sprintf("%v", this.DisallowedFlunders) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FischerList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]Fischer{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "Fischer", "Fischer", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&FischerList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *Flunder) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Flunder{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "FlunderSpec", "FlunderSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "FlunderStatus", "FlunderStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FlunderList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]Flunder{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "Flunder", "Flunder", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&FlunderList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v1.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *FlunderSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FlunderSpec{`,
		`Reference:` + fmt.Sprintf("%v", this.Reference) + `,`,
		`ReferenceType:` + valueToStringGenerated(this.ReferenceType) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FlunderStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FlunderStatus{`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Fischer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fischer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fischer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisallowedFlunders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisallowedFlunders = append(m.DisallowedFlunders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FischerList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FischerList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FischerList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, Fischer{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Flunder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Flunder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Flunder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FlunderList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlunderList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlunderList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, Flunder{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FlunderSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlunderSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlunderSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reference", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reference = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReferenceType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := ReferenceType(dAtA[iNdEx:postIndex])
			m.ReferenceType = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FlunderStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FlunderStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FlunderStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
